/**
 * Copyright (c) 2022 Luca Erbetta
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/*
 ******************************************************************************
 *                  THIS FILE IS AUTOGENERATED. DO NOT EDIT.                  *
 ******************************************************************************
 */

// Autogen date:    2022-07-17 18:57:49.066216

#include <cassert>
#include <cstdint>
#include <string>
#include <type_traits>

#include "Event.h"
#include "camera/CameraWrapper.h"
#include "fsm/CameraData.h"

enum Topics : uint8_t
{
    TOPIC_CAMERA_CONFIG,
    TOPIC_CAMERA_CMD,
    TOPIC_CAMERA_EVENT
};

string getTopicName(uint8_t topic);
uint8_t getTopicID(string topic_str);

struct EventCameraCmdConnect : public Event
{
    static constexpr uint16_t id = 10;

    EventCameraCmdConnect();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCmdDisconnect : public Event
{
    static constexpr uint16_t id = 11;

    EventCameraCmdDisconnect();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCmdRecoverError : public Event
{
    static constexpr uint16_t id = 12;

    EventCameraCmdRecoverError();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCmdCapture : public Event
{
    static constexpr uint16_t id = 13;

    EventCameraCmdCapture();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCmdCapture_Internal : public Event
{
    static constexpr uint16_t id = 14;

    EventCameraCmdCapture_Internal();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCmdDownload : public Event
{
    static constexpr uint16_t id = 15;

    EventCameraCmdDownload(bool download);

    string name() const override;

    string to_string() const override;

    bool download;
};

struct EventCameraCmdDownload_Internal : public Event
{
    static constexpr uint16_t id = 16;

    EventCameraCmdDownload_Internal();

    string name() const override;

    string to_string() const override;
};

struct EventCameraConnected : public Event
{
    static constexpr uint16_t id = 17;

    EventCameraConnected();

    string name() const override;

    string to_string() const override;
};

struct EventCameraDisconnected : public Event
{
    static constexpr uint16_t id = 18;

    EventCameraDisconnected();

    string name() const override;

    string to_string() const override;
};

struct EventCameraConnectionError : public Event
{
    static constexpr uint16_t id = 19;

    EventCameraConnectionError();

    string name() const override;

    string to_string() const override;
};

struct EventCameraError : public Event
{
    static constexpr uint16_t id = 20;

    EventCameraError();

    string name() const override;

    string to_string() const override;
};

struct EventCameraIgnoreError : public Event
{
    static constexpr uint16_t id = 21;

    EventCameraIgnoreError();

    string name() const override;

    string to_string() const override;
};

struct EventCameraCaptureDone : public Event
{
    static constexpr uint16_t id = 22;

    EventCameraCaptureDone(bool downloaded, string file);

    string name() const override;

    string to_string() const override;

    bool downloaded;
    string file;
};

struct EventCameraControllerState : public Event
{
    static constexpr uint16_t id = 23;

    EventCameraControllerState(uint8_t state);

    string name() const override;

    string to_string() const override;

    uint8_t state;
};

struct EventConfigSetShutterSpeed : public Event
{
    static constexpr uint16_t id = 24;

    EventConfigSetShutterSpeed(int32_t shutter_speed);

    string name() const override;

    string to_string() const override;

    int32_t shutter_speed;
};

struct EventConfigSetAperture : public Event
{
    static constexpr uint16_t id = 25;

    EventConfigSetAperture(int32_t aperture);

    string name() const override;

    string to_string() const override;

    int32_t aperture;
};

struct EventConfigSetISO : public Event
{
    static constexpr uint16_t id = 26;

    EventConfigSetISO(int32_t iso);

    string name() const override;

    string to_string() const override;

    int32_t iso;
};

struct EventConfigSetCaptureTarget : public Event
{
    static constexpr uint16_t id = 27;

    EventConfigSetCaptureTarget(string target);

    string name() const override;

    string to_string() const override;

    string target;
};

struct EventConfigGetShutterSpeed : public Event
{
    static constexpr uint16_t id = 28;

    EventConfigGetShutterSpeed();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueShutterSpeed : public Event
{
    static constexpr uint16_t id = 29;

    EventConfigValueShutterSpeed(gphotow::RadioMenuConfig shutter_speed);

    string name() const override;

    string to_string() const override;

    gphotow::RadioMenuConfig shutter_speed;
};

struct EventConfigGetAperture : public Event
{
    static constexpr uint16_t id = 30;

    EventConfigGetAperture();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueAperture : public Event
{
    static constexpr uint16_t id = 31;

    EventConfigValueAperture(gphotow::RadioMenuConfig aperture);

    string name() const override;

    string to_string() const override;

    gphotow::RadioMenuConfig aperture;
};

struct EventConfigGetISO : public Event
{
    static constexpr uint16_t id = 32;

    EventConfigGetISO();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueISO : public Event
{
    static constexpr uint16_t id = 33;

    EventConfigValueISO(gphotow::RadioMenuConfig iso);

    string name() const override;

    string to_string() const override;

    gphotow::RadioMenuConfig iso;
};

struct EventConfigGetBattery : public Event
{
    static constexpr uint16_t id = 34;

    EventConfigGetBattery();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueBattery : public Event
{
    static constexpr uint16_t id = 35;

    EventConfigValueBattery(int32_t battery);

    string name() const override;

    string to_string() const override;

    int32_t battery;
};

struct EventConfigGetFocalLength : public Event
{
    static constexpr uint16_t id = 36;

    EventConfigGetFocalLength();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueFocalLength : public Event
{
    static constexpr uint16_t id = 37;

    EventConfigValueFocalLength(int32_t focal_length);

    string name() const override;

    string to_string() const override;

    int32_t focal_length;
};

struct EventConfigGetFocusMode : public Event
{
    static constexpr uint16_t id = 38;

    EventConfigGetFocusMode();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueFocusMode : public Event
{
    static constexpr uint16_t id = 39;

    EventConfigValueFocusMode(gphotow::RadioMenuConfig focues_mode);

    string name() const override;

    string to_string() const override;

    gphotow::RadioMenuConfig focues_mode;
};

struct EventConfigGetLongExpNR : public Event
{
    static constexpr uint16_t id = 40;

    EventConfigGetLongExpNR();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueLongExpNR : public Event
{
    static constexpr uint16_t id = 41;

    EventConfigValueLongExpNR(bool long_exp_nr);

    string name() const override;

    string to_string() const override;

    bool long_exp_nr;
};

struct EventConfigGetVibRed : public Event
{
    static constexpr uint16_t id = 42;

    EventConfigGetVibRed();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueVibRed : public Event
{
    static constexpr uint16_t id = 43;

    EventConfigValueVibRed(gphotow::RadioMenuConfig vr);

    string name() const override;

    string to_string() const override;

    gphotow::RadioMenuConfig vr;
};

struct EventConfigGetCommon : public Event
{
    static constexpr uint16_t id = 44;

    EventConfigGetCommon();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueCommon : public Event
{
    static constexpr uint16_t id = 45;

    EventConfigValueCommon(CameraCommonConfig common_config);

    string name() const override;

    string to_string() const override;

    CameraCommonConfig common_config;
};

struct EventConfigGetCaptureTarget : public Event
{
    static constexpr uint16_t id = 46;

    EventConfigGetCaptureTarget();

    string name() const override;

    string to_string() const override;
};

struct EventConfigValueCaptureTarget : public Event
{
    static constexpr uint16_t id = 47;

    EventConfigValueCaptureTarget(string target);

    string name() const override;

    string to_string() const override;

    string target;
};
